# Generated by Django 3.2.5 on 2022-01-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_on']},
        ),
    ]
